/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPaymentEnrollmentIdRouteImport } from './routes/_authenticated/payment.$enrollmentId'
import { Route as AuthenticatedPortalLearnSlugRouteImport } from './routes/_authenticated/portal.learn.$slug'

const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentEnrollmentIdRoute =
  AuthenticatedPaymentEnrollmentIdRouteImport.update({
    id: '/payment/$enrollmentId',
    path: '/payment/$enrollmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalLearnSlugRoute =
  AuthenticatedPortalLearnSlugRouteImport.update({
    id: '/learn/$slug',
    path: '/learn/$slug',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/research': typeof ResearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/payment/$enrollmentId': typeof AuthenticatedPaymentEnrollmentIdRoute
  '/portal/learn/$slug': typeof AuthenticatedPortalLearnSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/research': typeof ResearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/payment/$enrollmentId': typeof AuthenticatedPaymentEnrollmentIdRoute
  '/portal/learn/$slug': typeof AuthenticatedPortalLearnSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/membership': typeof MembershipRoute
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/research': typeof ResearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/_authenticated/payment/$enrollmentId': typeof AuthenticatedPaymentEnrollmentIdRoute
  '/_authenticated/portal/learn/$slug': typeof AuthenticatedPortalLearnSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/forgot-password'
    | '/membership'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/research'
    | '/admin'
    | '/portal'
    | '/admin/login'
    | '/news/$slug'
    | '/programs/$slug'
    | '/reset-password/$token'
    | '/payment/$enrollmentId'
    | '/portal/learn/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/forgot-password'
    | '/membership'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/research'
    | '/admin'
    | '/portal'
    | '/admin/login'
    | '/news/$slug'
    | '/programs/$slug'
    | '/reset-password/$token'
    | '/payment/$enrollmentId'
    | '/portal/learn/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/forgot-password'
    | '/membership'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/research'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/admin/login'
    | '/news/$slug'
    | '/programs/$slug'
    | '/reset-password/$token'
    | '/_authenticated/payment/$enrollmentId'
    | '/_authenticated/portal/learn/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MembershipRoute: typeof MembershipRoute
  NewsRoute: typeof NewsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  ResearchRoute: typeof ResearchRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment/$enrollmentId': {
      id: '/_authenticated/payment/$enrollmentId'
      path: '/payment/$enrollmentId'
      fullPath: '/payment/$enrollmentId'
      preLoaderRoute: typeof AuthenticatedPaymentEnrollmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/learn/$slug': {
      id: '/_authenticated/portal/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/portal/learn/$slug'
      preLoaderRoute: typeof AuthenticatedPortalLearnSlugRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
  }
}

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalLearnSlugRoute: typeof AuthenticatedPortalLearnSlugRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalLearnSlugRoute: AuthenticatedPortalLearnSlugRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedPaymentEnrollmentIdRoute: typeof AuthenticatedPaymentEnrollmentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedPaymentEnrollmentIdRoute: AuthenticatedPaymentEnrollmentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ProgramsRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MembershipRoute: MembershipRoute,
  NewsRoute: NewsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  ResearchRoute: ResearchRoute,
  AdminLoginRoute: AdminLoginRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
