// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient(): SupabaseClient<Database> {
  // Use import.meta.env for client-side (Vite build-time replacement)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
  const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["VITE_SUPABASE_URL"] : []),
      ...(!SUPABASE_ANON_KEY ? ["VITE_SUPABASE_ANON_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Set them in .env or Vercel dashboard.`;
    console.error(`[Supabase] ${message}`);

    if (typeof window === "undefined") {
      console.warn(
        "[Supabase] SSR: env vars missing, returning stub client. This will fail gracefully on use instead of crashing SSR.",
      );
      return createSupabaseStub(
        `[Supabase] Env vars not configured. Check that VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set in Vercel dashboard.`,
      ) as any;
    }

    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? createBrowserAuthStorage() : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

function createBrowserAuthStorage() {
  const rememberPreferenceKey = "amtmti_remember_session";

  function preferredStorage() {
    return window.localStorage.getItem(rememberPreferenceKey) === "false"
      ? window.sessionStorage
      : window.localStorage;
  }

  return {
    getItem(key: string) {
      return window.localStorage.getItem(key) ?? window.sessionStorage.getItem(key);
    },
    setItem(key: string, value: string) {
      const target = preferredStorage();
      const fallback = target === window.localStorage ? window.sessionStorage : window.localStorage;
      fallback.removeItem(key);
      target.setItem(key, value);
    },
    removeItem(key: string) {
      window.localStorage.removeItem(key);
      window.sessionStorage.removeItem(key);
    },
  };
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

function createSupabaseStub(message: string): SupabaseClient<Database> {
  const error = new Error(message);
  const createProxy = (path: string[] = []): any => {
    const stub = (..._args: unknown[]): any => {
      const key = path.join(".");
      if (key === "auth.onAuthStateChange") {
        return { data: { subscription: { unsubscribe: () => undefined } } };
      }
      if (key === "auth.getSession") {
        return Promise.resolve({ data: { session: null } });
      }
      if (key === "auth.getUser") {
        return Promise.resolve({ data: { user: null } });
      }
      if (
        path[path.length - 1] === "select" ||
        path[path.length - 1] === "insert" ||
        path[path.length - 1] === "update" ||
        path[path.length - 1] === "delete" ||
        path[path.length - 1] === "upsert" ||
        path[path.length - 1] === "rpc" ||
        path[path.length - 1] === "maybeSingle" ||
        path[path.length - 1] === "single"
      ) {
        return Promise.reject(error);
      }
      return createProxy(path);
    };

    return new Proxy(stub as any, {
      get(_target, prop) {
        if (prop === "then") return undefined;
        return createProxy([...path, String(prop)]);
      },
      apply(_target, _thisArg, argArray) {
        return stub(...argArray);
      },
    });
  };

  return createProxy();
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
