// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
  const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["VITE_SUPABASE_URL"] : []),
      ...(!SUPABASE_ANON_KEY ? ["VITE_SUPABASE_ANON_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Set them in .env or Vercel dashboard.`;
    console.error(`[Supabase] ${message}`);
    
    // During SSR, if env vars are missing, don't throw — return a stub client
    // that will fail gracefully when actually used (client-side only).
    if (typeof window === "undefined") {
      console.warn("[Supabase] SSR: env vars missing, returning stub client. This will fail on client-side access.");
      // Return a dummy proxy that won't crash SSR but will error on use
      return new Proxy({} as ReturnType<typeof createClient>, {
        get: () => {
          throw new Error(
            `[Supabase] Env vars not configured. Check that VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set in Vercel dashboard.`
          );
        },
      });
    }
    
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
