// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export type SupabaseServerEnv = {
  SUPABASE_URL?: string;
  SUPABASE_SERVICE_ROLE_KEY?: string;
};

function createSupabaseAdminStub(message: string): SupabaseClient<Database> {
  const error = new Error(message);
  const createProxy = (path: string[] = []): any => {
    const stub = (..._args: unknown[]): any => {
      if (path[path.length - 1] === "select" || path[path.length - 1] === "insert" || path[path.length - 1] === "update" || path[path.length - 1] === "delete" || path[path.length - 1] === "upsert" || path[path.length - 1] === "rpc" || path[path.length - 1] === "maybeSingle" || path[path.length - 1] === "single") {
        return Promise.reject(error);
      }
      return createProxy(path);
    };

    return new Proxy(stub as any, {
      get(_target, prop) {
        if (prop === "then") return undefined;
        return createProxy([...path, String(prop)]);
      },
      apply(_target, _thisArg, argArray) {
        return stub(...argArray);
      },
    });
  };

  return createProxy();
}

export function createSupabaseAdminClient(env?: SupabaseServerEnv): SupabaseClient<Database> {
  const SUPABASE_URL = env?.SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = env?.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ["SUPABASE_SERVICE_ROLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase Admin] ${message}`);

    if (!process.env.SUPABASE_SERVICE_ROLE_KEY && process.env.NODE_ENV === "production") {
      console.warn(
        "[Supabase Admin] Production: service role key not set. Admin operations will fail at runtime."
      );
      return createSupabaseAdminStub(
        `[Supabase Admin] Not configured. SUPABASE_SERVICE_ROLE_KEY is required for admin operations.`,
      );
    }

    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}
